name: 'citibike_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'citibike_dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # This is the only path-related config needed
clean-targets: ["target", "dbt_packages"]

models:
  citibike_dbt_project:
    staging:
      +materialized: view
      +schema: staging
    core:
      +materialized: table
      +schema: analytics
    mart:
      +materialized: table
      +schema: analytics

vars:
  partition_by: "DATE(started_at)"  # Define as variable instead of direct config