de-zoomcamp-project-454319:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: de-zoomcamp-project-454319
      keyfile: /home/yassersakr88/de-zoomcamp/7_project/7.2_data_ingestion_dlt_kestra/gcs-service-account.json
      dataset: zoomcamp_project
      threads: 1
