citibike_dbt_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      project: citibike-zoomcamp-project
      dataset: citibike_tripdata
      threads: 4
      timeout_seconds: 300
      location: US